### ISSUE TITLE
No Clan weapons work anymore, only fire like IS tech

### ISSUE THREAD

**Issue by shadowfax13th** [BattletechModders/CustomComponents#12]
Rather than pulse lasers shooting three times, or UACs twice, the UACs dump all their damage in one shot and the pulse lasers are it seems only doing one shot with the damage one pulse would. Medium pulse for instance do 12 x 3 shots, but now it's one shot of 12.

**Comment by LadyAlekto** [comment]
this has nothing to do with CC

This sounds like you used roguetech files

So why the fuck are you spamming all these mods with issues pertaining rt?
