### ISSUE TITLE
Component Destroyed Error

### ISSUE THREAD

**Issue by Shivaxi** [BattletechModders/CustomComponents#21]
CptMoore kindly asked me to post my findings here:  2-fold issue

1.  if a location is completely destroyed, but also a component in that location has been destroyed, like the engine core, or something replacing the sensor slot in the head, the slot is suddenly missing when going to repair

![image](https://user-images.githubusercontent.com/10459358/210051447-334d6167-346f-481c-99db-c96c314100cf.png)

![image](https://user-images.githubusercontent.com/10459358/210051467-0216202d-a490-49d2-8222-cffd3a1c58ed.png)

adding the broken component back and then removing it will return the missing Sensors and Core Fusion Placeholder slots

The 2nd issue is somewhat related I think, where repairing all still throws out an error that critical components must still be repaired, even though they get repaired after validation anyway:

![image](https://user-images.githubusercontent.com/10459358/210051587-381f074f-001b-4b64-85ce-b54f08422678.png)

**Comment by CptMoore** [comment]
fixed in 5443991e10b4659b114e30371a0f8cd521665347
