### ISSUE TITLE
A flag to exclude categorys

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/CustomComponents#3]
A flag for categorys that allows to be forbidden if other categories are present on mech

as example for the list

{  "Name": "Supercharger",  "displayName": "Supercharger",  "MaxEquiped":  "1", "AutoReplace": "false", "Forbidden":"MASC"},
{  "Name": "TSM",  "displayName": "Triple Strength Myomer",  "MaxEquiped":  "6", "AutoReplace": "true","AddMaximumReached": "Mech already has {1} of {0} installed", "Forbidden":"MASC"},

**Comment by Denadan** [comment]
implemented
usage 
```
{ "Name": "Supercharger", "displayName": "Supercharger", "MaxEquiped": "1", "AutoReplace": "false", "Forbidden": ["MASC"] },
```
